### ISSUE TITLE
how can i flash this firmware to my anycubic tft?

### ISSUE THREAD

**Issue by sims-60** [louisvarley/Anycubic-i3-TFT-Firmware-Orange#1]

**Comment by sims-60** [comment]
and do you have discord?

**Comment by louisvarley** [comment]
Its SEAL Team Ricks#1150


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by louisvarley** [comment]
Add me and see what we can do. Depends on model you have but I needed a new screen

**Comment by sims-60** [comment]
i have the anycubic tft v0.0.2

**Comment by sims-60** [comment]
i have sent you a dc friend request
